#!/bin/bash
cd ~/astrometry-venv
export PATH=/usr/local/astrometry/bin/:$PATH
source bin/activate
solve-field --overwrite --no-background-subtraction -p -S /tmp/platesolveok $1 > /tmp/astroresult 2>&1
cat /tmp/astroresult | grep "Field center" | grep deg | cut -d'=' -f2 | sed -e "s/(//g" -e "s/)//g" -e "s/ deg.//g" -e s"/ //g" > /tmp/astro.result
