#!/bin/bash
cd ~/astrometry-venv
export PATH=/usr/local/astrometry/bin/:$PATH
source bin/activate
solve-field --overwrite --no-background-subtraction -p -S /tmp/platesolveok $1 > /tmp/astroresult 2>&1

coord=$(cat /tmp/astroresult | grep "Field center" | grep deg | cut -d'=' -f2 | sed -e "s/(//g" -e "s/)//g" -e "s/ deg.//g" -e s"/ //g")
angle=$(cat /tmp/astroresult | grep "Field rotation angle" | sed -E "s/.* (\-?[0-9\.]+).*/\1/")
echo $coord,$angle > /tmp/astro.result
